### ISSUE TITLE
subfolder

### ISSUE THREAD

**Issue by Mowen-M** [enchant97/note-mark#205] opened 2024-08-29 05:33 UTC
### Does it fit the projects scope?

- [X] This is relevant

### Why?

I know the issue of subfolder from last year someone else mentioned, but I would very much like to say subfolders are so important for a note take app. So, please have at least 2 subfolder, it's normal for a note take app. I want to use it!!! I looking for a good note take app for a long time. I tried joplin(which don't have a web app version), standard note(Mysql won't work), memos(it's not good at taking note). Please.

### Solution?

Please.

**Comment by enchant97** [comment] 2024-08-29 16:56
I do plan to add this in the future. However, it requires a lot of work to implement, due to how the note structure is stored in the database.

This is also a duplicate of #92.

**Closed by enchant97** 2024-08-29 16:56 UTC
Labels: enhancement
