### ISSUE TITLE
Disable user registration

### ISSUE THREAD

**Issue by ctrlbrk42** [enchant97/note-mark#172] opened 2024-01-01 20:26 UTC
I am the only user or I'll create another account as needed. I need to disable registration as this will sit on public facing network.

Set a env to disable please

**Comment by enchant97** [comment] 2024-01-01 21:14
Duplicate of #116. Take a look at the docs: https://notemark.docs.enchantedcode.co.uk/docs/setup/configuration/. There is a `ALLOW_SIGNUP` environment variable

**Closed by enchant97** 2024-01-01 21:14 UTC
